In [4]:
import numpy as np
import pandas as pd
from PIL import Image
import os

In [1]:
from fastseg import MobileV3Large

In [2]:
model = MobileV3Large(num_classes=19, use_aspp=True, num_filters=256)
model = model.from_pretrained(num_filters=256)

Loading pretrained model mobilev3large-lraspp with F=256...


In [5]:
img = Image.open("../data/utube/Kochi 4K _ Driving from Kakkanad to Kaloor by sunset 24-41 screenshot.png")
labels = model.predict_one(img)

In [6]:
labels.shape

(1080, 1920)

In [7]:
labels

array([[10, 10, 10, ...,  5,  5,  5],
       [10, 10, 10, ...,  5,  5,  5],
       [10, 10, 10, ...,  5,  5,  5],
       ...,
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0]])

In [8]:
classes, counts = np.unique(labels, return_counts=True)
classes, counts, counts.sum()

(array([ 0,  1,  2,  3,  4,  5,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18]),
 array([571909,  19333, 567996,  15262,  32790,  18517,   1460, 339605,
         42222, 307525,  13580,  10107,  76213,  16147,  19551,     13,
         20035,   1335]),
 2073600)

In [9]:
class_names = ["road", "sidewalk", "building", "wall", "fence", "pole", "traffic_light", "traffic_sign", "vegetation", "terrain", "sky", "person", "rider", "car", "truck", "bus", "train", "motorcycle", "bicycle"]
len(class_names)

19

In [10]:
img_class_counts = {}

In [11]:
img_dir = "../data/utube"

In [12]:
for img_path in os.listdir(img_dir):
    print(f"Processing image {img_path}")
    img = Image.open(os.path.join(img_dir, img_path))
    labels = model.predict_one(img)
    _, counts = np.unique(labels, return_counts=True)
    n_pixels = labels.size
    counts = counts/ n_pixels
    img_class_counts[img_path] = counts

Processing image 4K Drive in Kolkata _ East India_s Tier-1 City 13-20 screenshot.png
Processing image Driving in Bangalore 4K - Karnataka, India 35-47 screenshot.png
Processing image View_of_a_street_in_Hindu_Colony_locality_of_Dadar,_Mumbai.jpg


In [ ]:
img_class_counts

Error: Session cannot generate requests